### ISSUE TITLE
touch sensors stick

### ISSUE THREAD

**Issue by akaylyn** [akaylyn/simon#15]
During gameplay and bongo mode, the touch sensors have started registering a button press without a release.

## Branches
Oldest to Newest

:white_check_mark:  https://github.com/akaylyn/simon/commit/be5a34de2e51e94be88b103f7026df8e01063864
:red_circle:  https://github.com/akaylyn/simon/commit/c4c334fcb050cc9f91817394bbcd967cebf87693 the yellow button starts getting stuck at this build of Light.ino

**Comment by akaylyn** [comment]
Rolling back to https://github.com/akaylyn/simon/commit/be5a34de2e51e94be88b103f7026df8e01063864 is less sticky, but not perfect.

Running the MPR121_Test is *flawless*. All touches and releases are registered without a problem.

**Comment by akaylyn** [comment]
https://github.com/akaylyn/simon/commit/c4c334fcb050cc9f91817394bbcd967cebf87693 is the commit where the yellow button starts getting stuck. Reverting the changes in Light.ino, but keeping the rest.

**Comment by the-magister** [comment]
Why revert light.ino?

On Tuesday, July 7, 2015, Andrea Kaylyn Pollitt <notifications@github.com>
wrote:

> c4c334f
> <https://github.com/akaylyn/simon/commit/c4c334fcb050cc9f91817394bbcd967cebf87693>
> is the commit where the yellow button starts getting stuck. Reverting the
> changes in Light.ino, but keeping the rest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119414320>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by the-magister** [comment]
And, are the differences just in the mpr library?

Also, is Alan getting these emails?  Dunno git's distro.

On Tuesday, July 7, 2015, Andrea Kaylyn Pollitt <notifications@github.com>
wrote:

> c4c334f
> <https://github.com/akaylyn/simon/commit/c4c334fcb050cc9f91817394bbcd967cebf87693>
> is the commit where the yellow button starts getting stuck. Reverting the
> changes in Light.ino, but keeping the rest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119414320>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by akaylyn** [comment]
To determine if the touch sensor continues to stick prior to the changes made to Light.ino in this commit. The touch sensor does not get stuck during bongo/gameplay mode with the Console.ino being updated. I've tested both individually for each commit. If I can jump to HEAD with the Light.ino changes reverted and the sensor no longer sticks, I've successfully isolated the problem.

**Comment by the-magister** [comment]
Okay.

I need to ask again, as I've not gotten an affirmative response and it's an
important detail. Are you testing with programming cable disconnected with
the console only running from AC power?

On Tuesday, July 7, 2015, Andrea Kaylyn Pollitt <notifications@github.com>
wrote:

> To determine if the touch sensor continues to stick prior to the changes
> made to Light.ino in this commit. The touch sensor does not get stuck
> during bongo/gameplay mode with the Console.ino being updated. I've tested
> both individually for each commit. If I can jump to HEAD with the Light.ino
> changes reverted and the sensor no longer sticks, I've successfully
> isolated the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119415770>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by the-magister** [comment]
If it's traced to light.ino.... I've got no ideas. We were demonstrating
the issue without Light involved at all.

On Tuesday, July 7, 2015, Mike Dodds <magister@the-magister.com> wrote:

> Okay.
>
> I need to ask again, as I've not gotten an affirmative response and it's
> an important detail. Are you testing with programming cable disconnected
> with the console only running from AC power?
>
> On Tuesday, July 7, 2015, Andrea Kaylyn Pollitt <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> To determine if the touch sensor continues to stick prior to the changes
>> made to Light.ino in this commit. The touch sensor does not get stuck
>> during bongo/gameplay mode with the Console.ino being updated. I've tested
>> both individually for each commit. If I can jump to HEAD with the Light.ino
>> changes reverted and the sensor no longer sticks, I've successfully
>> isolated the problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akaylyn/simon/issues/15#issuecomment-119415770>.
>>
>
>
> --
> Mike Dodds
> magister@the-magister.com
> <javascript:_e(%7B%7D,'cvml','magister@the-magister.com');>
>
>

-- 
Mike Dodds
magister@the-magister.com

**Comment by akaylyn** [comment]
Yep, all tests are being done with only AC power running to the console.

**Comment by the-magister** [comment]
Good. Ok, thanks for taking a careful look at this. I'm confident you'll
get to the bottom of it. Check in with Alan for a test plan and CNW
release. I'd spare you'd the pain of programming in the field--not awesome.

I'm really curious as to the result, so loop me in when you can. There's
nothing I can do to affect the outcome from here, so I'm like a expecting
father pacing the halls.

Warm Regards,
Mike

On Tuesday, July 7, 2015, Andrea Kaylyn Pollitt <notifications@github.com>
wrote:

> Yep, all tests are being done with only AC power running to the console.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119420446>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by akaylyn** [comment]
Now that I've been working on the console for an hour+, https://github.com/akaylyn/simon/blob/master/tests/Console/MPR121_Test/MPR121_Test.ino is no longer working for the yellow button. Having the cover on doesn't seem to make a difference either.

I'm going to try printing out the values for each of the calibration press/release thresholds and see if the yellow button (the button located above the light mega) is somehow off.

**Comment by giles7777** [comment]
There is s tests Touch_Alan which had sticky ness without any light module running I just used sound module to hear presses

Having a usb device plugged in helped but didn't fix the issue completely 

Tweaking some mpr params on the mpr debug branch got it working more reliable or soemines it as fine for 5 mins but then would have errors.  This code does include a 3s loop break with recalibrate

**Comment by the-magister** [comment]
Touch_Mike has mpr library tweaked to allow fast baseline adaptation.
Buttons can't be held more than 7s (even real presses), but it won't hang.
See spreadsheet I sent re baseline adaptation settings.

It's a hack, but it might work.

On Wednesday, July 8, 2015, Alan Hudson <notifications@github.com> wrote:

> There is s tests Touch_Alan which had sticky ness without any light module
> running I just used sound module to hear presses
>
> Having a usb device plugged in helped but didn't fix the issue completely
>
> Tweaking some mpr params on the mpr debug branch got it working more
> reliable or soemines it as fine for 5 mins but then would have errors. This
> code does include a 3s loop break with recalibrate
>
> Sent from my iPhone
>
> > On Jul 8, 2015, at 12:55 AM, Andrea Kaylyn Pollitt <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Now that I've been working on the console for an hour+,
> https://github.com/akaylyn/simon/blob/master/tests/Console/MPR121_Test/MPR121_Test.ino
> is no longer working for the yellow button. Having the cover on doesn't
> seem to make a difference either.
> >
> > I'm going to try printing out the values for each of the calibration
> press/release thresholds and see if the yellow button (the button located
> above the light mega) is somehow off.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119570268>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by akaylyn** [comment]
Tonight I'm going to build a Faraday cage around the console mega. I was able to get the sensor to register touches consistently after picking the entire button up and out, then putting it back again. The acrylic top being on didn't seem to affect the yellow sensor's malfunction. Swapping the sensors resulted in the sensor above the mega malfunctioning still.

**Comment by akaylyn** [comment]
I will also check out the branches you both mentioned.

**Comment by the-magister** [comment]
Interesting. Cabling could produce emf. I'd expect the mega emf field to be
stable, however. Sole fluctuations due to signals.

Al foil is above chem bench. Foil tape in a bin I conducive, so you can tie
foil to ground.

If that works out, we can cut decorative panels from the stock right of the
electronics benches and mount that with standoff above mega.

On Wednesday, July 8, 2015, Andrea Kaylyn Pollitt <notifications@github.com>
wrote:

> Tonight I'm going to build a Faraday cage around the console mega. I was
> able to get the sensor to register touches consistently after picking the
> entire button up and out, then putting it back again. The acrylic top being
> on didn't seem to affect the yellow sensor's malfunction. Swapping the
> sensors resulted in the sensor above the mega malfunctioning still.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119634956>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by giles7777** [comment]
I did try putting aluminum foil above the mega and a paper towel neither isolated things but it was pretty janky

**Comment by the-magister** [comment]
You'd need to ground the foil. Look for "GND" pins at the opposite end from
the USB.

On Wednesday, July 8, 2015, Alan Hudson <notifications@github.com> wrote:

> I did try putting aluminum foil above the mega and a paper towel neither
> isolated things but it was pretty janky
>
> Sent from my iPhone
>
> > On Jul 8, 2015, at 11:58 AM, Andrea Kaylyn Pollitt <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Tonight I'm going to build a Faraday cage around the console mega. I was
> able to get the sensor to register touches consistently after picking the
> entire button up and out, then putting it back again. The acrylic top being
> on didn't seem to affect the yellow sensor's malfunction. Swapping the
> sensors resulted in the sensor above the mega malfunctioning still.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119665846>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by giles7777** [comment]
I can confirm I did not ground the foil so that's worth trying again.  Just
be careful as there are some exposed areas that foil could short with.  I
left a piece of foil roughly correct size on the white table.

**Comment by the-magister** [comment]
Could also try taping foil on the underside of the button acrylic and
grounding that.

We did confirm the baseline readings were similar between buttons, as I
recall. If emf was impacting, I'd guess it'd show up there.

On Wednesday, July 8, 2015, Alan Hudson <notifications@github.com> wrote:

> I can confirm I did not ground the foil so that's worth trying again. Just
> be careful as there are some exposed areas that foil could short with. I
> left a piece of foil roughly correct size on the white table.
>
> On Wed, Jul 8, 2015 at 10:07 AM, Alan Hudson <giles7777@gmail.com
> <javascript:_e(%7B%7D,'cvml','giles7777@gmail.com');>> wrote:
>
> > I did try putting aluminum foil above the mega and a paper towel neither
> > isolated things but it was pretty janky
> >
> > Sent from my iPhone
> >
> > On Jul 8, 2015, at 11:58 AM, Andrea Kaylyn Pollitt <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Tonight I'm going to build a Faraday cage around the console mega. I was
> > able to get the sensor to register touches consistently after picking the
> > entire button up and out, then putting it back again. The acrylic top
> being
> > on didn't seem to affect the yellow sensor's malfunction. Swapping the
> > sensors resulted in the sensor above the mega malfunctioning still.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/akaylyn/simon/issues/15#issuecomment-119634956>.
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-119775578>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by the-magister** [comment]
Andrea,

I think the branch is MPR121_debug or something. Libraries/bare.../mpr121.h
is heavily commented with what the hell he registers do. Therein, I poke
baseline drift settings in the Touched state. Allowing that to drift
quickly immediately resolves the stuck buttons.

The stock library allows no drift, which is counter to what the adafruit
and sparkfun libraries (the other two we evaluated) do. See the compare and
contrast spreadsheet.

Remember, at the outset I said we'd need to tune the touch
hardware/software to the production environment?  Yep, here we are. We can
throw some more hardware tweaks at it (I added a copper ground plane;
you're looking at emf shielding). With all of that in place (ie
best-possible hardware setup), we'd still need to tune.

On Wednesday, July 8, 2015, Mike Dodds <magister@the-magister.com> wrote:

> Could also try taping foil on the underside of the button acrylic and
> grounding that.
>
> We did confirm the baseline readings were similar between buttons, as I
> recall. If emf was impacting, I'd guess it'd show up there.
>
> On Wednesday, July 8, 2015, Alan Hudson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I can confirm I did not ground the foil so that's worth trying again. Just
>> be careful as there are some exposed areas that foil could short with. I
>> left a piece of foil roughly correct size on the white table.
>>
>> On Wed, Jul 8, 2015 at 10:07 AM, Alan Hudson <giles7777@gmail.com> wrote:
>>
>> > I did try putting aluminum foil above the mega and a paper towel neither
>> > isolated things but it was pretty janky
>> >
>> > Sent from my iPhone
>> >
>> > On Jul 8, 2015, at 11:58 AM, Andrea Kaylyn Pollitt <
>> > notifications@github.com> wrote:
>> >
>> > Tonight I'm going to build a Faraday cage around the console mega. I was
>> > able to get the sensor to register touches consistently after picking
>> the
>> > entire button up and out, then putting it back again. The acrylic top
>> being
>> > on didn't seem to affect the yellow sensor's malfunction. Swapping the
>> > sensors resulted in the sensor above the mega malfunctioning still.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/akaylyn/simon/issues/15#issuecomment-119634956>.
>> >
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akaylyn/simon/issues/15#issuecomment-119775578>.
>>
>
>
> --
> Mike Dodds
> magister@the-magister.com
> <javascript:_e(%7B%7D,'cvml','magister@the-magister.com');>
>
>

-- 
Mike Dodds
magister@the-magister.com

**Comment by akaylyn** [comment]
Grounding foil and placing it either over the mega or under the button did not seem to affect the touch sensor's ability to readjust its baseline and stop registering false positives.

I made a branch (apollitt-mpr121-config) off of Mike's Touch_Mike branch. 

https://github.com/akaylyn/simon/blob/apollitt-mpr121-config/tests/Console/MPR121_Test/MPR121_Test.ino#L78
```
void printTouchData() {
  uint16_t base0 = ((uint16_t)MPR121.getRegister(0x1E))<<2;
  uint16_t base1 = ((uint16_t)MPR121.getRegister(0x21))<<2;
  uint16_t data0 = (((uint16_t)MPR121.getRegister(0x05))<<8) + MPR121.getRegister(0x04);
  uint16_t data1 = (((uint16_t)MPR121.getRegister(0x0B))<<8) + MPR121.getRegister(0x0A);
  Serial << "0 " << base0 << " -- " << data0 << " || ";
  Serial << "3 " << base1 << " -- " << data1 << endl;
}
```
The format of the output is `sensor 0` `baseline` -- `data` || `sensor 3` `baseline` -- `data` 

In this test I consecutively pressed and released sensor 3 (yellow), and near the end it got stuck.

```
3 pressed.
0 724 -- 726 || 3 716 -- 725
3 released.
3 pressed.
0 724 -- 726 || 3 744 -- 646
3 released.
3 pressed.
3 released.
3 pressed.
0 724 -- 727 || 3 744 -- 695
0 724 -- 726 || 3 744 -- 709
0 724 -- 726 || 3 740 -- 711
0 724 -- 727 || 3 740 -- 711
0 724 -- 727 || 3 736 -- 711
0 724 -- 727 || 3 736 -- 711
0 724 -- 727 || 3 732 -- 712
0 724 -- 726 || 3 732 -- 712
0 724 -- 727 || 3 732 -- 712
3 released.
```

The new baseline was adjusted upwards to 744, when it should've been closer to 712. The new baseline was closer to 700 by the time I removed my hand. 

AN3891.pdf has the solution to this problem.

**Comment by the-magister** [comment]
That's my feeling, too, Andrea. Something in the baseline drift system
needs to be tuned up. Freescale does have a user community forum.

On Thursday, July 9, 2015, Andrea Kaylyn Pollitt <notifications@github.com>
wrote:

> Grounding foil and placing it either over the mega or under the button did
> not seem to affect the touch sensor's ability to readjust its baseline and
> stop registering false positives.
>
> I made a branch (apollitt-mpr121-config) off of Mike's Touch_Mike branch.
>
>
> https://github.com/akaylyn/simon/blob/apollitt-mpr121-config/tests/Console/MPR121_Test/MPR121_Test.ino#L78
>
> void printTouchData() {
>   uint16_t base0 = ((uint16_t)MPR121.getRegister(0x1E))<<2;
>   uint16_t base1 = ((uint16_t)MPR121.getRegister(0x21))<<2;
>   uint16_t data0 = (((uint16_t)MPR121.getRegister(0x05))<<8) + MPR121.getRegister(0x04);
>   uint16_t data1 = (((uint16_t)MPR121.getRegister(0x0B))<<8) + MPR121.getRegister(0x0A);
>   Serial << "0 " << base0 << " -- " << data0 << " || ";
>   Serial << "3 " << base1 << " -- " << data1 << endl;
> }
>
> The format of the output is sensor 0 baseline -- data || sensor 3 baseline
> -- data
>
> In this test I consecutively pressed and released sensor 3 (yellow), and
> near the end it got stuck.
>
> 3 pressed.
> 0 724 -- 726 || 3 716 -- 725
> 3 released.
> 3 pressed.
> 0 724 -- 726 || 3 744 -- 646
> 3 released.
> 3 pressed.
> 3 released.
> 3 pressed.
> 0 724 -- 727 || 3 744 -- 695
> 0 724 -- 726 || 3 744 -- 709
> 0 724 -- 726 || 3 740 -- 711
> 0 724 -- 727 || 3 740 -- 711
> 0 724 -- 727 || 3 736 -- 711
> 0 724 -- 727 || 3 736 -- 711
> 0 724 -- 727 || 3 732 -- 712
> 0 724 -- 726 || 3 732 -- 712
> 0 724 -- 727 || 3 732 -- 712
> 3 released.
>
> The new baseline was adjusted upwards to 744, when it should've been
> closer to 712. The new baseline was closer to 700 by the time I removed my
> hand.
>
> AN3891.pdf has the solution to this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-120232810>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by the-magister** [comment]
And, I made a spreadsheet to compare the baseline adaptation settings for
three libraries. Definitely magic numbers.

On Friday, July 10, 2015, Mike Dodds <magister@the-magister.com> wrote:

> That's my feeling, too, Andrea. Something in the baseline drift system
> needs to be tuned up. Freescale does have a user community forum.
>
> On Thursday, July 9, 2015, Andrea Kaylyn Pollitt <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Grounding foil and placing it either over the mega or under the button
>> did not seem to affect the touch sensor's ability to readjust its baseline
>> and stop registering false positives.
>>
>> I made a branch (apollitt-mpr121-config) off of Mike's Touch_Mike branch.
>>
>>
>> https://github.com/akaylyn/simon/blob/apollitt-mpr121-config/tests/Console/MPR121_Test/MPR121_Test.ino#L78
>>
>> void printTouchData() {
>>   uint16_t base0 = ((uint16_t)MPR121.getRegister(0x1E))<<2;
>>   uint16_t base1 = ((uint16_t)MPR121.getRegister(0x21))<<2;
>>   uint16_t data0 = (((uint16_t)MPR121.getRegister(0x05))<<8) + MPR121.getRegister(0x04);
>>   uint16_t data1 = (((uint16_t)MPR121.getRegister(0x0B))<<8) + MPR121.getRegister(0x0A);
>>   Serial << "0 " << base0 << " -- " << data0 << " || ";
>>   Serial << "3 " << base1 << " -- " << data1 << endl;
>> }
>>
>> The format of the output is sensor 0 baseline -- data || sensor 3
>> baseline -- data
>>
>> In this test I consecutively pressed and released sensor 3 (yellow), and
>> near the end it got stuck.
>>
>> 3 pressed.
>> 0 724 -- 726 || 3 716 -- 725
>> 3 released.
>> 3 pressed.
>> 0 724 -- 726 || 3 744 -- 646
>> 3 released.
>> 3 pressed.
>> 3 released.
>> 3 pressed.
>> 0 724 -- 727 || 3 744 -- 695
>> 0 724 -- 726 || 3 744 -- 709
>> 0 724 -- 726 || 3 740 -- 711
>> 0 724 -- 727 || 3 740 -- 711
>> 0 724 -- 727 || 3 736 -- 711
>> 0 724 -- 727 || 3 736 -- 711
>> 0 724 -- 727 || 3 732 -- 712
>> 0 724 -- 726 || 3 732 -- 712
>> 0 724 -- 727 || 3 732 -- 712
>> 3 released.
>>
>> The new baseline was adjusted upwards to 744, when it should've been
>> closer to 712. The new baseline was closer to 700 by the time I removed my
>> hand.
>>
>> AN3891.pdf has the solution to this problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akaylyn/simon/issues/15#issuecomment-120232810>.
>>
>
>
> --
> Mike Dodds
> magister@the-magister.com
> <javascript:_e(%7B%7D,'cvml','magister@the-magister.com');>
>
>

-- 
Mike Dodds
magister@the-magister.com

**Comment by the-magister** [comment]
This:
https://docs.google.com/spreadsheets/d/1i2sOAcJ5KH8D39t_vV1P_6YUVGhdzs-NQQZjtKksBrg/edit?usp=docslist_api

You can see that sparkfun and adafruit have far fewer tuned values (taking
1/0 very commonly, or 0xFF).  The bareconductive library may be highly
tuned for their touch shield (with integral pads; much smaller than ours).

**Comment by akaylyn** [comment]
Replaced the wire attached to the button. No more voltage drops. Tested the wire with the multimeter; unable to create a consistent connection near the end of the wire.

Thinking the acrylic glue raised the resistance in the wire, causing voltage to fluctuate. 

Fixed.

**Comment by giles7777** [comment]
Hot damn you just made my week!

**Comment by akaylyn** [comment]
1 minute of touch sensor data without any actual touches. x-axis is time, y-axis is the touch sensor readings.
![sensor0](https://cloud.githubusercontent.com/assets/2453636/8640100/0fe6988e-28a1-11e5-815d-b58c853b5f88.png)
![sensor3](https://cloud.githubusercontent.com/assets/2453636/8640101/1432e4b0-28a1-11e5-97e8-c6d5cddfd360.png)
As you can see, sensor 3 (yellow) had serious voltage drops for no apparent reason. I was under the impression the plastic touch sensor was defective. There'd be no way to calibrate the sensor to accommodate voltage drops that significantly.

**Comment by akaylyn** [comment]
I also merged my touch sensor config into master. Some of the changes for baseline drift are better. Shane was able to get the touch sensors stuck in bongo by holding them all down for some amount of time before those changes, but not after.

**Comment by giles7777** [comment]
I have some updates that make bongomode timeout more safely on a stuck
event that I can look at merging in.

Any chance we can sync mon or tues night together for a final software
approval?  I'm available either with tues having some loading going on for
camp.

**Comment by akaylyn** [comment]
Bongo mode no longer gets stuck in master. Either way, I'll be around Monday and Tuesday. If you have it ready, you can open a pull request and I'll take a look.

**Comment by the-magister** [comment]
Nice. Way to troubleshoot that hardware problem.

I think we might replace all wires but post CNW.

Nice job, Andrea. Take some pride in this win.

On Sunday, July 12, 2015, Alan Hudson <notifications@github.com> wrote:

> Hot damn you just made my week!
>
> Sent from my iPhone
>
> > On Jul 12, 2015, at 2:08 PM, Andrea Kaylyn Pollitt <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Replaced the wire attached to the button. No more voltage drops. Tested
> the wire with the multimeter; unable to create a consistent connection near
> the end of the wire.
> >
> > Thinking the acrylic glue raised the resistance in the wire, causing
> voltage to fluctuate.
> >
> > Fixed.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akaylyn/simon/issues/15#issuecomment-120762911>.
>


-- 
Mike Dodds
magister@the-magister.com

**Comment by aaronstj** [comment]
Huge win!  Well done, Andrea.  Tracking down electrical problems like that
SUCKS.
